### ISSUE TITLE
Why dash-daq in Dockerfile?

### ISSUE THREAD

**Issue by maulberto3** [jucyai/docker-dash#1]
Any particular reason?

**Comment by yaojiach** [comment]
Here's the doc: https://dash.plotly.com/dash-daq
It includes basic form components and more.

**Comment by maulberto3** [comment]
I meant I did not see where you used it in your app. Or maybe I overlooked it.

**Comment by yaojiach** [comment]
You are right. It was not used in the sample app. Just included in the boilerplate code since most likely it would be used in a real world app.
